services:
  webcam:
    build: .
    container_name: webcam
    volumes:
      - ./snapshots:/app/snapshots
    stdin_open: true
    tty: true
    environment:
      - TZ=America/Los_Angeles
      - DISCORD_WEBHOOK_URLS=${DISCORD_WEBHOOK_URLS}
    restart: unless-stopped

volumes:
  snapshots:

